# Configuration de base
title: Reddit Hyperlink Network Project
description: Analyse du réseau d'hyperliens sur Reddit

# URL du site
url: "https://ctordo.github.io"
baseurl: "/reddit-hyperlink-network-project-draft"

# Jekyll settings
markdown: kramdown
permalink: none

# Désactiver les features Beautiful Jekyll non nécessaires
navbar-links: {}  # Pas de liens dans la navbar

# Exclure les fichiers inutiles
exclude:
  - README.md
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore